name = "TuringCLIExample"
uuid = "843339f9-e47f-46d2-a0d4-2bfd543a186f"
authors = ["Jesse Perla <jesseperla@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
